
# Vars
export EDITOR="vim"
export ARCHFLAGS="-arch x86_64"

# Colors
export CLICOLOR=1
export LSCOLORS="GxFxCxDxBxegedabagaced"
alias ls='ls -alhG'
export GREP_OPTIONS='--color=auto'

# Git prompt
parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}
export PS1="\w\[\033[32m\]\$(parse_git_branch)\[\033[00m\]$ "
