
# Vars
export EDITOR="vim"
export ARCHFLAGS="-arch x86_64"

# Colors
export CLICOLOR=1
export LSCOLORS="GxFxCxDxBxegedabagaced"
alias ls='ls -alhG'
export GREP_OPTIONS='--color=auto'

# Prompt
export PS1="\w$ "
